version: 2
jobs:
  deploy:
    docker:
      - image: buildpack-deps:trusty

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Deploy app
          command: chmod +x ./scripts/deploy.sh && ./scripts/deploy.sh

workflows:
  version: 2

  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - develop
                - master
                - deploy-sandbox
                - ch-circleci-deploy-job-MMDP-788
